---

# Export the Satellite Library for the organization

- name: "Performing library export {{ content_export.name }}" # noqa: name[template]
  redhat.satellite.content_export_library:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    ca_path: "{{ content_export.ca_path | default(omit) }}"
    chunk_size_gb: "{{ content_export.chunk_size_gb | default(omit) }}"
    destination_server: "{{ content_export.destination_server | default(omit) }}"
    fail_on_missing_content: "{{ content_export.fail_on_missing_content | default(omit) }}"
    format: "{{ content_export.format | default(omit) }}"
    from_history_id: "{{ content_export.from_history_id | default(omit) }}"
    incremental: "{{ content_export.incremental | default(omit) }}"
  async: 36000
  poll: 0
  register: export_library_result
  tags:
    - tags_content_config
    - tags_content_exports
    - tags_library_exports

- name: "Waiting on export job to finish for Library {{ content_export.name }}"
  ansible.builtin.async_status:
    jid: "{{ export_library_result.ansible_job_id }}"
  register: job_result
  until: job_result is finished
  retries: 3600
  delay: 10
  tags:
    - tags_content_config
    - tags_content_exports
    - tags_library_exports

- name: Clean up async file
  ansible.builtin.async_status:
    jid: '{{ export_library_result.ansible_job_id }}'
    mode: cleanup
  tags:
    - tags_content_config
    - tags_content_exports
    - tags_library_exports
