---

# Export the Satellite repository for the organization

- name: "Performing cv_version export using format {{ content_export.name }}" # noqa: name[template]
  redhat.satellite.content_export_version:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    content_view: "{{ content_export.product }}"
    content_view_version: "{{ content_export.repository }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    ca_path: "{{ content_export.ca_path | default(omit) }}"
    chunk_size_gb: "{{ content_export.chunk_size_gb | default(omit) }}"
    destination_server: "{{ content_export.destination_server | default(omit) }}"
    format: "{{ content_export.format | default(omit) }}"
    from_history_id: "{{ content_export.from_history_id | default(omit) }}"
    incremental: "{{ content_export.incremental | default(omit) }}"
  async: 36000
  poll: 0
  register: export_cv_result
  tags:
    - tags_content_config
    - tags_content_exports
    - tags_content_view_exports

- name: "Waiting on export job to finish for cv_version {{ content_export.name }}"
  ansible.builtin.async_status:
    jid: "{{ export_cv_result.ansible_job_id }}"
  register: job_result
  until: job_result is finished
  retries: 3600
  delay: 10
  tags:
    - tags_content_config
    - tags_content_exports
    - tags_content_view_exports

- name: Clean up async file
  ansible.builtin.async_status:
    jid: '{{ export_cv_result.ansible_job_id }}'
    mode: cleanup
  tags:
    - tags_content_config
    - tags_content_exports
    - tags_content_view_exports
