---
- name: "Ensure that firewalld is installed"
  ansible.builtin.dnf:
    name: firewalld
    state: present
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_firewall
    - tags_satellite_before_sync

- name: "Ensure that iptables is not running or configured" # noqa: ignore-errors
  ansible.builtin.systemd:
    name: iptables
    state: stopped
    enabled: false
    masked: true
  ignore_errors: true
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_firewall
    - tags_satellite_before_sync

- name: "Ensure that the Firewalld service is enabled and running"
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
    masked: false
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_firewall
    - tags_satellite_before_sync

- name: "Set the primary interface for Satellite communication"
  when: override_iface is defined and (sat_override_iface | length) > 0
  ansible.builtin.set_fact:
    sat_firewalld_interface: "{{ override_iface }}"
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_firewall
    - tags_satellite_before_sync

- name: "Configure Firewalld services and ports for Satellite"
  ansible.builtin.include_role:
    name: "redhat.rhel_system_roles.firewall"
  vars:
    firewall:                                                                     # noqa: var-naming[no-role-prefix]
      - { set_default_zone: "{{ sat_firewalld_zone }}",
          state: enabled }
      - { interface: "{{ sat_firewalld_interface }}",
          zone: "{{ sat_firewalld_zone }}",
          state: enabled }
      - { service: "RH-Satellite-6",
          port: ["5646/tcp", "8888/tcp", "8889/tcp", "5671/tcp", "5671/udp"],
          permanent: true,
          state: present }
      - { service: "{{ sat_firewalld_services }}",
          permanent: true,
          state: enabled }
  tags:
    - tags_satellite_pre
    - tags_satellite_pre_firewall
    - tags_satellite_before_sync
