---

- name: "Ensure satellite system registered to CDN"
  community.general.redhat_subscription:
    activationkey: "{{ cdn_sat_activation_key }}"
    org_id: "{{ cdn_organization_id }}"
    state: present
  tags:
    - tags_satellite_pre
    - tags_satellite_before_sync
