---

# tags don't flow through external roles
# This is one of the reasons for run_role.yml and run_role_task.yml
# This will not upgrade the satellite even if you have chnaged the repos
# please run upgrades interactively

- name: "Install the Satellite server with specified configuration."
  ansible.builtin.import_role:
    name: "redhat.satellite_operations.installer"
  vars:
    satellite_installer_scenario: "satellite"                   # noqa: var-naming[no-role-prefix]
    satellite_installer_options: "{{ sat_installer_options }}"
    satellite_installer_verbose: "{{ sat_installer_verbose }}"
  no_log: true
  tags:
    - tags_satellite_install
    - tags_satellite_before_sync
