---

# import the Satellite repository for the organization

- name: "Performing cv_version import using format {{ content_import.name }}" # noqa: name[template]
  redhat.satellite.content_import_version:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    ca_path: "{{ content_import.ca_path | default(omit) }}"
    metadata: "{{ content_import.metadata | default(omit) }}"
    metadata_file: "{{ content_import.metadata_file | default(omit) }}"
    path: "{{ content_import.import_path }}"
  async: 36000
  poll: 0
  register: import_cv_result
  tags:
    - tags_content_config
    - tags_content_imports
    - tags_content_view_imports

- name: "Waiting on import job to finish for cv_version {{ content_import.name }}"
  ansible.builtin.async_status:
    jid: "{{ import_cv_result.ansible_job_id }}"
  register: job_result
  until: job_result is finished
  retries: 3600
  delay: 10
  tags:
    - tags_content_config
    - tags_content_imports
    - tags_content_view_imports

- name: Clean up async file
  ansible.builtin.async_status:
    jid: '{{ import_cv_result.ansible_job_id }}'
    mode: cleanup
  tags:
    - tags_content_config
    - tags_content_imports
    - tags_content_view_imports
