---
## Configure the activation keys

- name: "Configure the activation_keys"
  when: activation_keys is defined and (activation_keys | length) > 0
  ansible.builtin.include_tasks: "ensure_activation_key.yml"
  loop: "{{ activation_keys }}"
  loop_control:
    loop_var: activation_key
  no_log: true
  tags:
    - tags_content_config
    - tags_activation_keys
