---

- name: "Configure the git repos to replicate"
  when: "git_repos is defined and (git_repos | length) > 0"
  ansible.builtin.include_tasks: "ensure_clone_git_repos.yml"
  loop: "{{ git_repos }}"
  loop_control:
    loop_var: gitrepo
  no_log: true
  tags:
    - tags_provisioning_config
    - tags_import_git_repos
