---
# Download the specified manifest from the portal
#
- name: "Remove existing manifest files from path"
  ansible.builtin.file:
    path: "{{ redhat_manifest.path }}"
    state: absent

- name: "Download the specified manifest from the portal if generating"
  when: redhat_manifest.generate
  redhat.satellite.redhat_manifest:
    portal: "{{ redhat_manifest.portal_url }}"
    username: "{{ redhat_manifest.cdn_username }}"
    password: "{{ redhat_manifest.cdn_password }}"
    validate_certs: "{{ redhat_manifest.validate_certs }}"
    name: "{{ redhat_manifest.name }}"
    path: "{{ redhat_manifest.path }}"

- name: "Upload the specified manifest from source if user provided"
  when: not redhat_manifest.generate
  ansible.builtin.copy:
    src: "{{ redhat_manifest.source }}"
    dest: "{{ redhat_manifest.path }}"
    owner: "root"
    group: "root"
    mode: "0600"
