#  There are really two aspects to manifests.
#  1. Creating, modifying, and deleting a manifest on the portal. And fetching the manifest..
#  2. Uploading, refreshing and replacing manifests on the Satellite

# This module only deals with item 1.
# A manifest must be created or a manifest must already exist
# Manifest creation data is sensitive, so should be vaulted and encrypted.

# We will fail if there are no manifests listed.

- name: "Ensure the manifests are configured in the portal"
  when: "redhat_manifests is defined and (redhat_manifests | length) > 0"
  ansible.builtin.include_tasks: "ensure_redhat_manifest.yml"
  loop: "{{ redhat_manifests }}"
  loop_control:
    loop_var: redhat_manifest
  no_log: true
  tags:
    - tags_user
    - tags_redhat_manifests
